#!/bin/bash

# ------------------------- [START] set shell options ------------------------ #
# exit script immediately if anything errors
set -e

# allow tracing to be toggled on
if [ "$DEBUG_GKE_GLUSTERFS_HEKETI" = 'true' ]
then
  set -x
fi
# -------------------------- [END] set shell options ------------------------- #

# ------------------------- [START] get project path ------------------------- #
# get full path to this project
project_dir="$(cd -P -- "$(dirname -- "$0")" 2>&1 > /dev/null && pwd -P)"

# check that the project directory didn't turn out empty
if [ -z "$project_dir" ]
then
  echo "Some error occured getting the full path to this project's directory."

  # this is intended to be sourced instead of executed so we return
  # instead of exiting so we don't exit the shell session entirely
  return 1
fi
# -------------------------- [END] get project path -------------------------- #

# ------------------------ [START] source config file ------------------------ #
. "$project_dir/config"
# ------------------------- [END] source config file ------------------------- #

# ---------------------- [START] set required variables ---------------------- #
export project_name="$CLOUDSDK_PROJECT_NAME"
export cluster_name="$CLOUDSDK_CLUSTER_NAME"
export zone="$CLOUDSDK_COMPUTE_ZONE"
export region="$CLOUDSDK_COMPUTE_REGION"
export heketi_keyadmin="$HEKETI_KEYADMIN"
export heketi_keyuser="$HEKETI_KEYUSER"
export gluster_image_name=${GLUSTER_IMAGE_NAME:-'gluster/gluster-centos:latest'}
# ----------------------- [END] set required variables ----------------------- #

# ---------------------- [START] set optional variables ---------------------- #
# cluster version will default to whatever GKE's default is at the time
export cluster_version="$CLUSTER_VERSION"
export node_count=${NODE_COUNT:-'1'}
export machine_type=${MACHINE_TYPE:-'n1-standard-1'}
export disk_size=${DISK_SIZE:-'20'}
export disk_type=${DISK_TYPE:-'pd-ssd'}

export docker_registry=${DOCKER_REGISTRY:-"gcr.io/$project_name"}
export docker_image_name=${DOCKER_IMAGE_NAME:-'glusterfs-heketi-bootstrap'}
export docker_image_version=${DOCKER_IMAGE_VERSION:-'0.0.1'}

if [ -z "$DOCKER_IMAGE_NAME" ]
then
  # my public dockerhub
  export job_image='stevenaldinger/gke-glusterfs-heketi:latest'
else
  # my private gcr repo
  export job_image="gcr.io/$project_name/$docker_image_name:$docker_image_version"
fi
# ----------------------- [END] set optional variables ----------------------- #

# ---------------- [START] ensure script requirements are met ---------------- #
script_requirements_met='true'

if [ -z "$(which gcloud)" ]
then
  echo "You need gcloud installed."
  echo "Visit https://cloud.google.com/sdk/downloads to download the latest version."

  script_requirements_met='false'
fi

if [ -z "$(which kubectl)" ]
then
  echo "You need kubectl installed."
  echo "If you already have gcloud installed, run 'gcloud components install kubectl'."
  script_requirements_met='false'
fi

if [ -z "$project_name" ] || [ -z "$cluster_name" ] || [ -z "$region" ]
then
  echo "You're missing required config variables."
  echo "Make sure there are values for everything under \"required variables\" in $project_dir/config"

  script_requirements_met='false'
fi

if [ "$node_count" -lt 1 ]
then
  echo "You need at least 3 nodes in the cluster for Heketi to run properly"

  script_requirements_met='false'
fi

if [ "$script_requirements_met" = 'false' ]
then
  # this is intended to be sourced instead of executed so we return
  # instead of exiting so we don't exit the shell session entirely
  return 1
fi
# ----------------- [END] ensure script requirements are met ----------------- #

# ------------------------- [START] helper functions ------------------------- #
trim_whitespace () {
	local var=$@
  # remove leading whitespace characters
	var="${var#"${var%%[![:space:]]*}"}"
  # remove trailing whitespace characters
	var="${var%"${var##*[![:space:]]}"}"
	echo -n "$var"
}


gke_glusterfs_heketi_build_image () {
  if [ -z "$(which docker)" ]
  then
    echo "You need docker installed to build this image."
  else
    docker build --no-cache -t "$docker_registry/$docker_image_name:$docker_image_version" "$project_dir"
  fi
}

gke_glusterfs_heketi_push_image () {
  docker push "$docker_registry/$docker_image_name:$docker_image_version"
}

gke_glusterfs_heketi_generate_k8s () {
  rm -rf "$project_dir/k8s"

  mkdir -p "$project_dir/k8s"

  cat > "$project_dir/k8s/00-namespace.yaml" <<EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: glusterfs-heketi-bootstrap
EOF

  cat > "$project_dir/k8s/01-heketi-serviceaccount.yaml" <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin
  namespace: glusterfs-heketi-bootstrap
EOF

cat > "$project_dir/k8s/01-configmap.yaml" <<EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glusterfs-heketi-bootstrap
  namespace: glusterfs-heketi-bootstrap
data:
  project-id: $project_name
  cluster-name: $cluster_name
  cluster-region: $region
  cluster-node-count: "$node_count"
  disk-size: "$disk_size"
  disk-type: "$disk_type"
  heketi-keyadmin: $heketi_keyadmin
  heketi-keyuser: $heketi_keyuser
  gluster-image-name: $gluster_image_name
EOF

cat > "$project_dir/k8s/01-heketi-clusterrole.yaml" <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list","delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list","get","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["replicationcontrollers"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
EOF

cat > "$project_dir/k8s/01-heketi-clusterrolebinding.yaml" <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glusterfs-heketi-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: glusterfs-heketi-bootstrap
    namespace: glusterfs-heketi-bootstrap
  - kind: ServiceAccount
    name: glusterfs-heketi-bootstrap
    namespace: default
EOF

cat > "$project_dir/k8s/02-job.yaml" <<EOF
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glusterfs-heketi-bootstrap
  namespace: glusterfs-heketi-bootstrap
spec:
  template:
    metadata:
      name: glusterfs-heketi-bootstrap
    spec:
      serviceAccountName: glusterfs-heketi-bootstrap
      restartPolicy: Never
      containers:
      - name: glusterfs-heketi-bootstrap
        image: $job_image
        securityContext:
          capabilities: {}
          privileged: true
        env:
        - name: PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: project-id
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-name
        - name: GLUSTER_IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: gluster_image_name
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-region
        - name: NODE_COUNT
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: cluster-node-count
        - name: DISK_SIZE
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: disk-size
        - name: DISK_TYPE
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: disk-type
        - name: HEKETI_KEYADMIN
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: heketi-keyadmin
        - name: HEKETI_KEYUSER
          valueFrom:
            configMapKeyRef:
              name: glusterfs-heketi-bootstrap
              key: heketi-keyuser
EOF
}

gke_glusterfs_heketi_delete_gluster_disks () {
  #FIXME This doesn't work now because the cluster and nodes are delted first,
  # and then we can't lookup the disks via the node names. Need to dump a list of
  # disks and check the namme
  IFS=$'\n'

  #Get list of nodes and zones as we have to create the disk in the correct zone for the correct node
  for CLUSTERZONES in $(gcloud compute zones list --format="table[no-heading](name)" --filter="region=$region")
  do
    # Parse (zone) --> $ZONE
    IFS=$' ' read -r ZONE <<<"${CLUSTERZONES}"
    echo -e "Zone:  ${ZONE}"
    echo ""

    #If there's more disks created, update this to delete additional disks.
    gcloud compute disks delete --zone $ZONE ${cluster_name}-${ZONE}-disk-1

  done
  unset IFS
}

gke_glusterfs_heketi_deploy_glusterfs_heketi () {
  kubectl apply -f "$project_dir/k8s"
}

gke_glusterfs_heketi_create_cluster () {
  "$project_dir/scripts/create-cluster.sh"
}

_gke_glusterfs_heketi_create_service_account () {
  kubectl create serviceaccount \
    glusterfs-heketi-bootstrap \
    --namespace glusterfs-heketi-bootstrap
}

_gke_glusterfs_heketi_add_admin_clusterrolebinding () {
  kubectl apply -f "$project_dir/k8s/01-heketi-clusterrole.yaml"
  kubectl apply -f "$project_dir/k8s/01-heketi-clusterrolebinding.yaml"
}

_gke_glusterfs_heketi_allow_own_user_rbac_admin () {
  # outputs something like this:
  # account = me@stevenaldinger.com
  email_unclean=$(gcloud config list | grep account)

  # remove the 'account = '
  email_clean_untrimmed=${email_unclean#*=}

  email_clean="$(trim_whitespace $email_clean_untrimmed)"

  kubectl create clusterrolebinding \
    "$email_clean-cluster-admin-binding" \
    "--clusterrole=cluster-admin" \
    "--user=$email_clean"
}

_gke_glusterfs_heketi_allow_default_compute_rbac_admin () {
  # outputs something like this:
  # Compute Engine default service account  789491211420-compute@developer.gserviceaccount.com
  email_unclean=$(gcloud iam service-accounts list | grep "Compute Engine default service account")

  # remove the 'Compute Engine default service account '
  email_unclean_untrimmed=${email_unclean#*"service account"}

  # remove the 'False' from the end
  email_clean_untrimmed=${email_unclean_untrimmed%False*}

  email_clean="$(trim_whitespace $email_clean_untrimmed)"

  kubectl create clusterrolebinding \
    "$email_clean-cluster-admin-binding" \
    "--clusterrole=cluster-admin" \
    "--user=$email_clean"

  # needed for heketi master branch
  kubectl create clusterrolebinding \
    "heketi-sa-view" \
    "--clusterrole=edit" \
    "--serviceaccount=default:heketi-service-account" \
    "--user=$email_clean"

}

gke_glusterfs_heketi_configure_rbac () {
  # requires namespace already be created
  kubectl apply -f k8s/00-namespace.yaml

  _gke_glusterfs_heketi_allow_own_user_rbac_admin

  # default_compute necessary to avoid error during job:
  # Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "789491211420-compute@developer.gserviceaccount.com" cannot create clusterrolebindings.rbac.authorization.k8s.io at the cluster scope: Required "container.clusterRoleBindings.create" permission.
  # Error from server (NotFound): clusterrolebindings.rbac.authorization.k8s.io "heketi-sa-view" not found
  _gke_glusterfs_heketi_allow_default_compute_rbac_admin

  _gke_glusterfs_heketi_create_service_account

  _gke_glusterfs_heketi_add_admin_clusterrolebinding
}

gke_glusterfs_heketi_delete_cluster () {
  gcloud container clusters delete "$cluster_name" --region $region
}

gke_glusterfs_heketi_delete_cluster_and_disks () {
  gke_glusterfs_heketi_delete_cluster && \
  gke_glusterfs_heketi_delete_gluster_disks && \
  gcloud compute firewall-rules delete allow-$cluster_name-glusterfs
  gcloud compute firewall-rules delete allow-$cluster_name-heketi
}

gke_glusterfs_heketi_tail_job_logs () {
  kubectl -n glusterfs-heketi-bootstrap logs -f "$(kubectl get po -n glusterfs-heketi-bootstrap -l job-name=glusterfs-heketi-bootstrap -o jsonpath='{.items[0].metadata.name}')"
}

gke_glusterfs_heketi_if_storage_class_not_found_during_k8s_example_run_me () {
  external_ip_first_node=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
  heketi_nodeport=$(kubectl get svc/heketi -n default -o jsonpath='{.spec.ports[0].nodePort}')

  storage_class_yaml_path="$project_dir/k8s/heketi-glusterfs-storage-class.yaml"

  # ---------------- [START] Generate storage class descriptor ----------------- #
  cat > "$storage_class_yaml_path" <<EOF
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://${external_ip_first_node}:${heketi_nodeport}"
  restuser: "user"
  restuserkey: "user"
  
EOF
  # ----------------- [END] Generate storage class descriptor ------------------ #

  # ----------------------- [START] Apply storage class ------------------------ #
  kubectl apply -f "$storage_class_yaml_path"
  # ------------------------ [END] Apply storage class ------------------------- #
}
# -------------------------- [END] helper functions -------------------------- #

# --------------------------- [START] print config --------------------------- #
echo "---------------------------------------------"
echo "Setup Functions Available:"
echo "#1 gke_glusterfs_heketi_build_image"
echo "#2 gke_glusterfs_heketi_push_image"
echo "#3 gke_glusterfs_heketi_generate_k8s"
echo "#4 (optional) gke_glusterfs_heketi_create_cluster"
echo "#5 gke_glusterfs_heketi_configure_rbac"
echo "#6 gke_glusterfs_heketi_deploy_glusterfs_heketi"
echo "#7 gke_glusterfs_heketi_tail_job_logs"
echo ""
echo "---------------------------------------------"
echo "Teardown Functions Available:"
echo "Only Disks:   gke_glusterfs_heketi_delete_gluster_disks"
echo "Only Cluster: gke_glusterfs_heketi_delete_cluster"
echo "Everything:   gke_glusterfs_heketi_delete_cluster_and_disks"
echo ""
echo "---------------------------------------------"
echo "Current config:"
echo "- CLOUDSDK_PROJECT_NAME = $project_name"
echo "- CLOUDSDK_CLUSTER_NAME = $cluster_name"
echo "- CLOUDSDK_COMPUTE_REGION = $region"
echo "- CLUSTER_VERSION       = $cluster_version"
echo "- NODE_COUNT            = $node_count"
echo "- MACHINE_TYPE          = $machine_type"
echo "- DOCKER_REGISTRY       = $docker_registry"
echo "- DOCKER_IMAGE_NAME     = $docker_image_name"
echo "- DOCKER_IMAGE_VERSION  = $docker_image_version"
echo "- GLUSTER_IMAGE_NAME    = $gluster_image_name"
echo "---------------------------------------------"
# ---------------------------- [END] print config ---------------------------- #

# --------------- [START] execute command if argument provided --------------- #
if [ ! -z "$1" ]
then
  $1
else
  echo ""
  echo "This script can be run with arguments or by sourcing and calling the functions directly."
  echo "Try './helpers gke_glusterfs_heketi_build_image'"
fi
# ---------------- [END] execute command if argument provided ---------------- #

# ------------------------ [START] unset shell options ----------------------- #
# exit script immediately if anything errors
set +e

# allow tracing to be toggled on
if [ "$DEBUG_GKE_GLUSTERFS_HEKETI" = 'true' ]
then
  set +x
fi
# ------------------------- [END] unset shell options ------------------------ #
