---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: percona
  namespace: default
  labels:
    app: example-percona
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
