apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: default
  labels:
    app: mariadb
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-storage"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
