apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: default
  labels:
    app: mariadb
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
