---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: default
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        app: mariadb
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.26.2"
        imagePullPolicy: Always
        command:
        - "rm"
        - "-rf"
        - "/var/lib/mysql/lost+found"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-volume
      containers:
      - name: mariadb
        image: mariadb:10.3.1
        args:
        - mysqld
        - --bind-address=0.0.0.0
        ports:
        - name: sql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sql
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: password
        volumeMounts:
        - name: mariadb-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-volume
        persistentVolumeClaim:
          claimName: mariadb
