---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: default
  labels:
    app: example-wordpress
spec:
  accessModes:
  - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "glusterfs-storage"
