---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    component: wordpress
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      component: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: wordpress
      name: wordpress
      namespace: default
    spec:
      restartPolicy: Always
      containers:
      - image: wordpress:4.9.8
        imagePullPolicy: IfNotPresent
        name: wordpress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sql
              key: db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: sql
              key: db-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: password
        volumeMounts:
          - name: wordpress-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress
