---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: wordpress
  namespace: default
  labels:
    component: wordpress
spec:
  serviceName: wordpress
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: wordpress
      namespace: default
      labels:
        component: wordpress
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: wordpress
        image: wordpress:4.9.8
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: sql
              key: db-host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: sql
              key: db-name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: password
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress
